# Strausz pasta {#Strausz-pasta .unnumbered}

*I have been making this for many years, ever since an Italian friend of Kate and me taught me how to make a version. I adapted it a bit based on a pasta that my old friend Jon Knoll taught me to make. I called the pasta that Jon made "Knoll Pasta," so I call this Strausz Pasta.*

**Ingredients:**  
1 oz dried porcine or other flavorful mushrooms (I have used shiitake too)  
8-10 cloves of garlic (**not frozen or powdered**), minced  
1/3 c extra virgin olive oil (plus more for sauteing mushrooms and onions)  
1 lb mushrooms (any kind), chopped  
1 onion, chopped  
1 pound pasta  

**Steps:**  

1. Cover dried mushrooms in water, and leave them on low heat for at least 15 minutes; more is fine.
2. Combine garlic with olive oil, a bit of salt and pepper. Simmer over medium-low until the garlic just starts to color. This may take a long time -- at least 15 minutes.
3. Once dried mushrooms are done, drain them in a colander lined with paper towel.  
4. Cut mushrooms, and saute in more olive oil over medium in a large pan with fresh mushrooms and onions. Saute until they have a good deal of color on them.
5. Cook pasta in salted water. Reserve about 1/3 cup of the cooking liquid.
6. Combine olive oil, garlic, mushrooms, onions, 1/3 cup mushroom water, and 1/3 cup pasta cooking water. Season with salt and pepper to taste. 
7. **Add a bit of salt to the rest of the mushroom water and keep it as a veggie broth for other uses.**
