# Salmon in wine reduction {.unnumbered}

*This is a very easy dish to make, but it doesn't taste like it. I based it on <a href="https://www.seriouseats.com/just-add-water-how-to-make-a-pan-sauce-and-how-to-fix-a-broken-one">instructions from Serious Eats</a>, one of my favorite cooking sites. I often cook it with with rice and a vegetable, and then I use some of the leftover rice to make [fried rice](#fried-rice).* 

**Ingredients:**  
Between 1 and 2 lbs salmon fillets  
3 cloves garlic, minced (fresh is always better, but it is less important here than with [Strausz pasta](#Strausz-pasta))  
1/2 cup red wine (the recipe will also work with white wine)  
1 cup broth (I often use the leftover mushroom water from [Strausz pasta](#Strausz-pasta)  
1 tablespoon butter, cut into small pieces

**Steps:**  

1. Heat a large cast iron skillet to medium for a while (5-10 minutes)
2. Add some olive oil to the pan put salmon fillets, flesh side down, on the skillet for 5 minutes. Turn, and cook for 5 minutes on the other side, and check inside of fish for doneness. If it is not done, cook for another minute and try again.
3. Remove salmon from oven and put on a plate. You can put another plate on top, upside down, to keep it warm.
4. Add a bit of olive oil to pan, and scrape the pan with a spatula to get the "fond" from the fish. This will make the sauce yummier.
5. Add the garlic to the pan along with a bit of salt, and stir for about about 15 seconds.
6. Add wine and reduce to what the French call *au sec* (almost dry). You should be able to scrape a spatula through it and leave a trail.
7. Add broth and scatter butter throughout the sauce. Whisk until the sauce looks creamy, thick, and opaque. Taste for seasoning, and add salt and pepper if necessary. Pour sauce in a bowl, sprinkle some over the fillets, and serve with the rest of the sauce.

*Instead of or in addition to garlic, you can use shallots, cumin, paprika, and/or other aromatics when you add the garlic.*
