# Fried rice {#fried-rice .unnumbered}

*This is my version of the Mark Bittman's recipe from <a href="https://www.howtocookeverything.com/home">How to Cook Everything</a>. It is one of the dishes that I have been making the longest, and it is one of Kate's favorites. Fried rice is often said to be better with leftover rice. These are instructions for a cast iron skillet because I don't think you have a wok, but if you get one let me know and I will update the recipe! The eggs give it some nice protein, but you can also add tofu or other cooked meat if you want. You can include any diced vegetables. If you want to add some spinach, you can add it at the same time you add the eggs.*

**Ingredients:**  
vegetable oil  
Around 3 cups leftover rice (can be brown or white)  
1 onion or green onions, diced  
1 carrot, diced  
3 stalks celery, diced   
2 cloves garlic, minced  
2 eggs, beaten  
2 Tablespoons soy sauce (you can use some hoisin sauce, vegan oyster sauce, or other sauces that appeal to you instead or in addition)  
Sesame seeds (optional)  

**Steps:**  

1. Heat a large cast iron skillet to medium for a while (5-10 minutes)
2. Add some vegetable oil, and then add the rice, and spread out in the pan.
3. Leave it stirred for 1-2 minutes, and then stir/turn the rice. Repeat until the rice has a nice texture
3. Add the carrots, onions, celery, and other vegetables, and stir for a few minutes, until they are cooked.
4. Make a well in the center of the rice. Add a bit more oil, and then the garlic. Let the garlic sizzle for about 15 seconds.
5. Add eggs to the well, and start to stir. Gradually incorporate rice into egg scramble.
6. Remove from heat and stir in soy sauce and sesame seeds.
