# Matza ball soup {#matza-ball .unnumbered}
<div style="text-align: center"> 
"We wasted that group like matza ball soup"<br>
-*The Making of Rafi Schwartz, the Ultimate Kung Fu Jew*
</div>

*This is a version of the soup that I made for Passover a few years ago.*

**Ingredients:**  
1 oz dried mushrooms (shiitakes or porchini work well, but anything will do)  
Olive oil  
1 sweet potato, diced  
1 onion, diced  
3 pieces celery, diced  
1 lb mushrooms, sliced about 1 cm thick  
1 carrot, diced  
1 sweet potato, diced  
1 package of matza balls (you can also make them from scratch; I like the recipe associated with <a href="https://smittenkitchen.com/2008/02/matzo-ball-soup/">this soup</a>)

**Steps:**  
1. Boil water, and pour over the dried mushrooms. Let the mushrooms reconstitute for at least 15 minutes (longer is ok).  
2. Drain mushrooms into a metal colander lined with paper towel, and save the liquid (that will be your broth). Salt the mushroom water.  
3. Heat oil in a big pot over medium. Once it is hot, add all your vegetables (including teh mushrooms that had been dried before. Cook for about 10 minutes.  
4. Add between 8 - 12 cups of liquid total (the salted mushroom water + regular water to bring you to 8 - 12 cups). Season with salt and paper.  
5. Bring to a boil and then turn heat down. 
6. Cook the matza balls in the soup following package directions or the directions from the recipe you are using. Serve as soon as the matza balls are ready. Don't simmer endlessly or the vegetables will get mushy.  
