# Herbed rice with tahdig {#tahdig .unnumbered}

*This is a slight modification of <a href="https://cooking.nytimes.com/recipes/1018646-sabzi-polo-herbed-rice-with-tahdig">Samin Nosrat's amazing recipe from the New York Times</a>.  She recommends a 10-inch cast iron pan, and I have made adjustments for a 12-inch pan.*

**Ingredients:**  
2 cups basmati rice  
5 tablespoons unsalted butter  
4 cups finely diced leeks, including the dark green parts (2 medium leeks or 1 very large leek)
salt  
1/4 teaspoon ground turmeric  
1 cup finely chopped dill leaves and tender stems (about 2 bunches)  
1 cup finely chopped cilantro leaves and tender stems (about 2 large bunches)  
3 tablespoons Greek yogurt  
3 tablespoons neutral-tasting oil, such as canola  

**Steps:**  
1. Place rice in a bowl and rinse with cold water. Swirl vigorously with your fingers to release the starch, and change the water at least five times, until it runs clear. Once the water runs clear, let rice soak for 30 minutes.  
2. Fill a large stockpot with 4 quarts of water (16 cups). Cover and bring to a boil over high heat.  
3. Set a very well-seasoned 12-inch cast-iron skillet over medium heat and add 2 tablespoons butter. When butter melts, add leeks and a pinch of salt. Cook for 10 to 12 minutes, stirring occasionally, until tender.  
4. Once water comes to a boil, season it very heavily with either 6 tablespoons fine sea salt or a generous ½ cup kosher salt and the ground turmeric. (Don’t worry about oversalting; the rice will spend only a few minutes in this water.) Drain rice, then add it to the pot and stir. Set a fine-mesh sieve or colander in the sink. Cook rice, stirring occasionally, until al dente, 5 to 7 minutes. Drain into the sieve, then rinse with cold water to keep rice from cooking further. Drain rice well and place in a large bowl.  
5. Add leeks, dill and cilantro to rice. Stir well to combine. Taste and adjust seasoning with salt if needed. Remove 1 heaping cup of the rice mixture to a small bowl and mix with yogurt.  
6. Rinse and dry the skillet and return it to medium heat. Add remaining 3 tablespoons butter and the oil. When butter melts, add rice-yogurt mixture and spread it out into a thin, even layer with a heatproof spatula.  
7. Pile remaining rice into the pan, mounding it gently toward the center. Using the handle of a wooden spoon, gently dig 6 holes into the rice down to the bottom of the pot, which will be barely sizzling. Dig 5 of the holes about 2 inches from the sides of the pan, and put one in the center. (The holes will allow steam to escape from the bottommost layer of rice and allow a crisp crust to form.) There should be enough oil in the pan that you can see it bubbling up the sides; add a little more oil along the edges of the rice if needed to see these bubbles.  
8. Continue cooking rice over medium-high heat for 8 minutes, or until evenly browned along the edges, rotating the pan a half turn after 4 minutes to ensure even browning. Wrap a lid with a kitchen towel and cover pan. Turn the heat as low as it will go and continue cooking another 45 minutes, rotating the pan a quarter turn every 10 to 12 minutes. The rice is done when it’s cooked completely through.  
9. To unmold the rice, carefully run an offset spatula or butter knife along the edges of the pan to ensure that no part of the crust is sticking. Tip out any excess fat at the bottom of the pan into a bowl, gather your courage, and then carefully flip it onto a platter or cutting board. Serve immediately.  
